import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
    {
        id: 1,
        label: 'STUDENTS',
        isTitle: true,
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ETUDIANT'],
    },
    {
        id: 2,
        label: 'Add Student',
        icon: 'bx bx-user-plus',
        link: '/user/addStudent',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 3,
        label: 'Students',
        icon: 'bx bx-group',
        link: '/user/student-users',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ENCADRANT'],
    },
    {
        id: 4,
        label: 'SUPERVISORS',
        isTitle: true,
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 5,
        label: 'Add Supervisor',
        icon: 'bx bx-user-plus',
        link: '/user/addSupervisor',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 6,
        label: 'Supervisors',
        icon: 'bx bx-group',
        link: '/user/supervisor-users',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 12,
        label: 'Validate Supervisors',
        icon: 'bx bx-select-multiple',  
        link: '/serviceStage',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 7,
        label: 'ADMINS',
        isTitle: true,
        role:['CHEF_DEPARTEMENT'],
    },
    {
        id: 8,
        label: 'Intership Service Users',
        icon: 'bx bxs-user-detail',
        link: '/user/intership-service-users',
        role:['CHEF_DEPARTEMENT'],
    },
    {
        id: 9,
        label: 'STAGES',
        isTitle: true,
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ENCADRANT','ETUDIANT'],
    },
    {
        id: 10,
        label: 'Student Monitoring',
        icon: 'bx bx-plus',
        link: '/stage',
        role:['ENCADRANT'],
    },
    {
        id: 11,
        label: 'Internship Request',
        icon: 'bx bxs-folder-plus',
        link: '/processusStage',
        role:['ETUDIANT'],
    },
    {
        id: 13,
        label: 'Internships',
        icon: 'bx bx-data',
        link: '/stageList',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 13,
        label: 'Evaluate Internship',
        icon: 'bx bxs-shield-alt-2',
        link: '/gererNote',
        role:['ENCADRANT'],
    },
    {
        id: 14,
        label: 'INTERSHIP OFFRES',
        isTitle: true,
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ENCADRANT','ETUDIANT'],
    },
    {
        id: 14,
        label: 'Add Offer',
        icon: 'bx bxs-detail',
        link: '/offre',
        role:['ENCADRANT','SERVICE_STAGE','CHEF_DEPARTEMENT'],
    },
    {
        id: 15,
        label: 'Offers',
        icon: 'bx bxs-notepad',
        link: '/listeencadrant',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ENCADRANT'],
    },
    {
        id: 16,
        label: 'Offers List',
        icon: 'bx bxs-notepad',
        link: '/listedesoffre',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ENCADRANT','ETUDIANT'],
    },
    {
        id: 17,
        label: 'FORUM',
        isTitle: true,
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ETUDIANT','ENCADRANT'],
    },
    {
        id: 18,
        label: 'Add Question',
        icon: 'bx bx-message-alt-dots',
        link: '/addquestion',
        role:['ENCADRANT','ETUDIANT'],
    },
    {
        id: 18,
        label: 'Forums',
        icon: 'bx bxs-chat',
        link: '/listforum',
        role:['CHEF_DEPARTEMENT','SERVICE_STAGE','ENCADRANT','ETUDIANT'],
    },
    {
        id: 19,
        label: 'Favorites list',
        icon: 'bx bx-bookmarks',
        link: '/listFavoris',
        role:['ENCADRANT','ETUDIANT','CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 20,
        label: 'History',
        icon: 'bx bxs-book-content',
        link: '/historique',
        role:['ENCADRANT','ETUDIANT','CHEF_DEPARTEMENT','SERVICE_STAGE'],
    },
    {
        id: 22,
        label: 'EVENT',
        isTitle: true,
        role:['ENCADRANT'],
    },
    {
        id: 23,
        label: 'Event Calender',
        icon: 'bx bx-calendar-event',
        link: '/calendrier',
        role:['ENCADRANT'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT','SERVICE_STAGE'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT'],
    },
    {
        id: 23,
        label: '',
        role:['ETUDIANT'],
    },
    
   
];

